//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.WSSeguridad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BancoABC.com/Seguridad/", ConfigurationName="WSSeguridad.Seguridad")]
    public interface Seguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/Seguridad/AutenticarUsuario", ReplyAction="*")]
        MvcApplication1.WSSeguridad.AutenticarUsuarioResponse AutenticarUsuario(MvcApplication1.WSSeguridad.AutenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/Seguridad/AutenticarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication1.WSSeguridad.AutenticarUsuarioResponse> AutenticarUsuarioAsync(MvcApplication1.WSSeguridad.AutenticarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usuario", Namespace="http://www.BancoABC.com/Seguridad/", Order=0)]
        public MvcApplication1.WSSeguridad.AutenticarUsuarioRequestBody Body;
        
        public AutenticarUsuarioRequest() {
        }
        
        public AutenticarUsuarioRequest(MvcApplication1.WSSeguridad.AutenticarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AutenticarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public AutenticarUsuarioRequestBody() {
        }
        
        public AutenticarUsuarioRequestBody(string Usuario, string Password) {
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioAutenticado", Namespace="http://www.BancoABC.com/Seguridad/", Order=0)]
        public MvcApplication1.WSSeguridad.AutenticarUsuarioResponseBody Body;
        
        public AutenticarUsuarioResponse() {
        }
        
        public AutenticarUsuarioResponse(MvcApplication1.WSSeguridad.AutenticarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AutenticarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Result;
        
        public AutenticarUsuarioResponseBody() {
        }
        
        public AutenticarUsuarioResponseBody(string Mensaje, bool Result) {
            this.Mensaje = Mensaje;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeguridadChannel : MvcApplication1.WSSeguridad.Seguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadClient : System.ServiceModel.ClientBase<MvcApplication1.WSSeguridad.Seguridad>, MvcApplication1.WSSeguridad.Seguridad {
        
        public SeguridadClient() {
        }
        
        public SeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.WSSeguridad.AutenticarUsuarioResponse MvcApplication1.WSSeguridad.Seguridad.AutenticarUsuario(MvcApplication1.WSSeguridad.AutenticarUsuarioRequest request) {
            return base.Channel.AutenticarUsuario(request);
        }
        
        public string AutenticarUsuario(string Usuario, string Password, out bool Result) {
            MvcApplication1.WSSeguridad.AutenticarUsuarioRequest inValue = new MvcApplication1.WSSeguridad.AutenticarUsuarioRequest();
            inValue.Body = new MvcApplication1.WSSeguridad.AutenticarUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            MvcApplication1.WSSeguridad.AutenticarUsuarioResponse retVal = ((MvcApplication1.WSSeguridad.Seguridad)(this)).AutenticarUsuario(inValue);
            Result = retVal.Body.Result;
            return retVal.Body.Mensaje;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication1.WSSeguridad.AutenticarUsuarioResponse> MvcApplication1.WSSeguridad.Seguridad.AutenticarUsuarioAsync(MvcApplication1.WSSeguridad.AutenticarUsuarioRequest request) {
            return base.Channel.AutenticarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.WSSeguridad.AutenticarUsuarioResponse> AutenticarUsuarioAsync(string Usuario, string Password) {
            MvcApplication1.WSSeguridad.AutenticarUsuarioRequest inValue = new MvcApplication1.WSSeguridad.AutenticarUsuarioRequest();
            inValue.Body = new MvcApplication1.WSSeguridad.AutenticarUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Password = Password;
            return ((MvcApplication1.WSSeguridad.Seguridad)(this)).AutenticarUsuarioAsync(inValue);
        }
    }
}
