//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.WSConsultarPago {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BancoABC.com/ConsultaSaldo/", ConfigurationName="WSConsultarPago.ConsultaSaldo")]
    public interface ConsultaSaldo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/ConsultaSaldo/ConsultaSaldoPagar", ReplyAction="*")]
        MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponse ConsultaSaldoPagar(MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/ConsultaSaldo/ConsultaSaldoPagar", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponse> ConsultaSaldoPagarAsync(MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoPagarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoPagar", Namespace="http://www.BancoABC.com/ConsultaSaldo/", Order=0)]
        public MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequestBody Body;
        
        public ConsultaSaldoPagarRequest() {
        }
        
        public ConsultaSaldoPagarRequest(MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultaSaldoPagarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoServicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NoFactura;
        
        public ConsultaSaldoPagarRequestBody() {
        }
        
        public ConsultaSaldoPagarRequestBody(string TipoServicio, string NoFactura) {
            this.TipoServicio = TipoServicio;
            this.NoFactura = NoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoPagarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoPagarResponse", Namespace="http://www.BancoABC.com/ConsultaSaldo/", Order=0)]
        public MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponseBody Body;
        
        public ConsultaSaldoPagarResponse() {
        }
        
        public ConsultaSaldoPagarResponse(MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BancoABC/EntidadComun")]
    public partial class ConsultaSaldoPagarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Result;
        
        public ConsultaSaldoPagarResponseBody() {
        }
        
        public ConsultaSaldoPagarResponseBody(string Mensaje, bool Result) {
            this.Mensaje = Mensaje;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaSaldoChannel : MvcApplication1.WSConsultarPago.ConsultaSaldo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaSaldoClient : System.ServiceModel.ClientBase<MvcApplication1.WSConsultarPago.ConsultaSaldo>, MvcApplication1.WSConsultarPago.ConsultaSaldo {
        
        public ConsultaSaldoClient() {
        }
        
        public ConsultaSaldoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaSaldoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaSaldoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaSaldoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponse MvcApplication1.WSConsultarPago.ConsultaSaldo.ConsultaSaldoPagar(MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest request) {
            return base.Channel.ConsultaSaldoPagar(request);
        }
        
        public string ConsultaSaldoPagar(string TipoServicio, string NoFactura, out bool Result) {
            MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest inValue = new MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest();
            inValue.Body = new MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequestBody();
            inValue.Body.TipoServicio = TipoServicio;
            inValue.Body.NoFactura = NoFactura;
            MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponse retVal = ((MvcApplication1.WSConsultarPago.ConsultaSaldo)(this)).ConsultaSaldoPagar(inValue);
            Result = retVal.Body.Result;
            return retVal.Body.Mensaje;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponse> MvcApplication1.WSConsultarPago.ConsultaSaldo.ConsultaSaldoPagarAsync(MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest request) {
            return base.Channel.ConsultaSaldoPagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.WSConsultarPago.ConsultaSaldoPagarResponse> ConsultaSaldoPagarAsync(string TipoServicio, string NoFactura) {
            MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest inValue = new MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequest();
            inValue.Body = new MvcApplication1.WSConsultarPago.ConsultaSaldoPagarRequestBody();
            inValue.Body.TipoServicio = TipoServicio;
            inValue.Body.NoFactura = NoFactura;
            return ((MvcApplication1.WSConsultarPago.ConsultaSaldo)(this)).ConsultaSaldoPagarAsync(inValue);
        }
    }
}
