<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.BancoABC.com/CompensaII/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CompensaII" targetNamespace="http://www.BancoABC.com/CompensaII/" xmlns:xsd1="http://www.BancoABC/EntidadComun">
    <wsdl:import namespace="http://www.BancoABC/EntidadComun" location="EntidadComun.xsd"></wsdl:import>
    <wsdl:types>
    <xsd:schema targetNamespace="http://www.BancoABC.com/CompensaII/">
            <xsd:import schemaLocation="EntidadComun.xsd" namespace="http://www.BancoABC/EntidadComun"></xsd:import>
            <xsd:element name="Compensacion" type="xsd1:MensajePago">
      </xsd:element>
      <xsd:element name="CompensacionResponse" type="xsd1:MensajeTransaccion">
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CompensacionRequest">
    <wsdl:part element="tns:Compensacion" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="CompensacionResponse">
    <wsdl:part element="tns:CompensacionResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="CompensaII">
    <wsdl:operation name="Compensacion">
      <wsdl:input message="tns:CompensacionRequest"/>
      <wsdl:output message="tns:CompensacionResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CompensaIISOAP" type="tns:CompensaII">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Compensacion">
      <soap:operation soapAction="http://www.BancoABC.com/CompensaII/Compensacion"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CompensaII">
    <wsdl:port binding="tns:CompensaIISOAP" name="CompensaIISOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
