//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.WSNotificacionUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BancoABC.com/NotificarUsuario/", ConfigurationName="WSNotificacionUsuario.NotificarUsuario")]
    public interface NotificarUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/NotificarUsuario/NotificarUsuario", ReplyAction="*")]
        MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponse NotificarUsuario(MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/NotificarUsuario/NotificarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponse> NotificarUsuarioAsync(MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotificarUsuario", Namespace="http://www.BancoABC.com/NotificarUsuario/", Order=0)]
        public MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequestBody Body;
        
        public NotificarUsuarioRequest() {
        }
        
        public NotificarUsuarioRequest(MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class NotificarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mensaje;
        
        public NotificarUsuarioRequestBody() {
        }
        
        public NotificarUsuarioRequestBody(string From, string To, string Mensaje) {
            this.From = From;
            this.To = To;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotificarUsuarioResponse", Namespace="http://www.BancoABC.com/NotificarUsuario/", Order=0)]
        public MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponseBody Body;
        
        public NotificarUsuarioResponse() {
        }
        
        public NotificarUsuarioResponse(MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BancoABC/EntidadComun")]
    public partial class NotificarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Result;
        
        public NotificarUsuarioResponseBody() {
        }
        
        public NotificarUsuarioResponseBody(string Mensaje, bool Result) {
            this.Mensaje = Mensaje;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificarUsuarioChannel : MvcApplication1.WSNotificacionUsuario.NotificarUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificarUsuarioClient : System.ServiceModel.ClientBase<MvcApplication1.WSNotificacionUsuario.NotificarUsuario>, MvcApplication1.WSNotificacionUsuario.NotificarUsuario {
        
        public NotificarUsuarioClient() {
        }
        
        public NotificarUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificarUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificarUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificarUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponse MvcApplication1.WSNotificacionUsuario.NotificarUsuario.NotificarUsuario(MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest request) {
            return base.Channel.NotificarUsuario(request);
        }
        
        public bool NotificarUsuario(string From, string To, ref string Mensaje) {
            MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest inValue = new MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest();
            inValue.Body = new MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequestBody();
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.Mensaje = Mensaje;
            MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponse retVal = ((MvcApplication1.WSNotificacionUsuario.NotificarUsuario)(this)).NotificarUsuario(inValue);
            Mensaje = retVal.Body.Mensaje;
            return retVal.Body.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponse> MvcApplication1.WSNotificacionUsuario.NotificarUsuario.NotificarUsuarioAsync(MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest request) {
            return base.Channel.NotificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.WSNotificacionUsuario.NotificarUsuarioResponse> NotificarUsuarioAsync(string From, string To, string Mensaje) {
            MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest inValue = new MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequest();
            inValue.Body = new MvcApplication1.WSNotificacionUsuario.NotificarUsuarioRequestBody();
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.Mensaje = Mensaje;
            return ((MvcApplication1.WSNotificacionUsuario.NotificarUsuario)(this)).NotificarUsuarioAsync(inValue);
        }
    }
}
