//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.WSCompensar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BancoABC.com/CompensaII/", ConfigurationName="WSCompensar.CompensaII")]
    public interface CompensaII {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/CompensaII/Compensacion", ReplyAction="*")]
        MvcApplication1.WSCompensar.CompensacionResponse Compensacion(MvcApplication1.WSCompensar.CompensacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/CompensaII/Compensacion", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication1.WSCompensar.CompensacionResponse> CompensacionAsync(MvcApplication1.WSCompensar.CompensacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompensacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Compensacion", Namespace="http://www.BancoABC.com/CompensaII/", Order=0)]
        public MvcApplication1.WSCompensar.CompensacionRequestBody Body;
        
        public CompensacionRequest() {
        }
        
        public CompensacionRequest(MvcApplication1.WSCompensar.CompensacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BancoABC/EntidadComun")]
    public partial class CompensacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoServicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NoFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IdProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double ValorFactura;
        
        public CompensacionRequestBody() {
        }
        
        public CompensacionRequestBody(string TipoServicio, string NoFactura, string IdProducto, double ValorFactura) {
            this.TipoServicio = TipoServicio;
            this.NoFactura = NoFactura;
            this.IdProducto = IdProducto;
            this.ValorFactura = ValorFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompensacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompensacionResponse", Namespace="http://www.BancoABC.com/CompensaII/", Order=0)]
        public MvcApplication1.WSCompensar.CompensacionResponseBody Body;
        
        public CompensacionResponse() {
        }
        
        public CompensacionResponse(MvcApplication1.WSCompensar.CompensacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BancoABC/EntidadComun")]
    public partial class CompensacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Result;
        
        public CompensacionResponseBody() {
        }
        
        public CompensacionResponseBody(string Mensaje, bool Result) {
            this.Mensaje = Mensaje;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompensaIIChannel : MvcApplication1.WSCompensar.CompensaII, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompensaIIClient : System.ServiceModel.ClientBase<MvcApplication1.WSCompensar.CompensaII>, MvcApplication1.WSCompensar.CompensaII {
        
        public CompensaIIClient() {
        }
        
        public CompensaIIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompensaIIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompensaIIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompensaIIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.WSCompensar.CompensacionResponse MvcApplication1.WSCompensar.CompensaII.Compensacion(MvcApplication1.WSCompensar.CompensacionRequest request) {
            return base.Channel.Compensacion(request);
        }
        
        public string Compensacion(string TipoServicio, string NoFactura, string IdProducto, double ValorFactura, out bool Result) {
            MvcApplication1.WSCompensar.CompensacionRequest inValue = new MvcApplication1.WSCompensar.CompensacionRequest();
            inValue.Body = new MvcApplication1.WSCompensar.CompensacionRequestBody();
            inValue.Body.TipoServicio = TipoServicio;
            inValue.Body.NoFactura = NoFactura;
            inValue.Body.IdProducto = IdProducto;
            inValue.Body.ValorFactura = ValorFactura;
            MvcApplication1.WSCompensar.CompensacionResponse retVal = ((MvcApplication1.WSCompensar.CompensaII)(this)).Compensacion(inValue);
            Result = retVal.Body.Result;
            return retVal.Body.Mensaje;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication1.WSCompensar.CompensacionResponse> MvcApplication1.WSCompensar.CompensaII.CompensacionAsync(MvcApplication1.WSCompensar.CompensacionRequest request) {
            return base.Channel.CompensacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.WSCompensar.CompensacionResponse> CompensacionAsync(string TipoServicio, string NoFactura, string IdProducto, double ValorFactura) {
            MvcApplication1.WSCompensar.CompensacionRequest inValue = new MvcApplication1.WSCompensar.CompensacionRequest();
            inValue.Body = new MvcApplication1.WSCompensar.CompensacionRequestBody();
            inValue.Body.TipoServicio = TipoServicio;
            inValue.Body.NoFactura = NoFactura;
            inValue.Body.IdProducto = IdProducto;
            inValue.Body.ValorFactura = ValorFactura;
            return ((MvcApplication1.WSCompensar.CompensaII)(this)).CompensacionAsync(inValue);
        }
    }
}
