//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.WSConsultarSaldo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BancoABC.com/ConsultaSaldo/", ConfigurationName="WSConsultarSaldo.ConsultaSaldo")]
    public interface ConsultaSaldo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/ConsultaSaldo/ConsultaSaldoPagar", ReplyAction="*")]
        MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarResponse ConsultaSaldoPagar(MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoPagarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoPagar", Namespace="http://www.BancoABC.com/ConsultaSaldo/", Order=0)]
        public MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarRequestBody Body;
        
        public ConsultaSaldoPagarRequest() {
        }
        
        public ConsultaSaldoPagarRequest(MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultaSaldoPagarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoServicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NoFactura;
        
        public ConsultaSaldoPagarRequestBody() {
        }
        
        public ConsultaSaldoPagarRequestBody(string TipoServicio, string NoFactura) {
            this.TipoServicio = TipoServicio;
            this.NoFactura = NoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoPagarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoPagarResponse", Namespace="http://www.BancoABC.com/ConsultaSaldo/", Order=0)]
        public MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarResponseBody Body;
        
        public ConsultaSaldoPagarResponse() {
        }
        
        public ConsultaSaldoPagarResponse(MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultaSaldoPagarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referenciaFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalPagar;
        
        public ConsultaSaldoPagarResponseBody() {
        }
        
        public ConsultaSaldoPagarResponseBody(string referenciaFactura, double totalPagar) {
            this.referenciaFactura = referenciaFactura;
            this.totalPagar = totalPagar;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaSaldoChannel : MvcApplication1.WSConsultarSaldo.ConsultaSaldo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaSaldoClient : System.ServiceModel.ClientBase<MvcApplication1.WSConsultarSaldo.ConsultaSaldo>, MvcApplication1.WSConsultarSaldo.ConsultaSaldo {
        
        public ConsultaSaldoClient() {
        }
        
        public ConsultaSaldoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaSaldoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaSaldoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaSaldoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarResponse ConsultaSaldoPagar(MvcApplication1.WSConsultarSaldo.ConsultaSaldoPagarRequest request) {
            return base.Channel.ConsultaSaldoPagar(request);
        }
    }
}
