//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.WSVerificarSaldo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BancoABC.com/VerificarSaldo/", ConfigurationName="WSVerificarSaldo.VerificarSaldo")]
    public interface VerificarSaldo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/VerificarSaldo/VerificarSaldo", ReplyAction="*")]
        MvcApplication1.WSVerificarSaldo.VerificarSaldoResponse VerificarSaldo(MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BancoABC.com/VerificarSaldo/VerificarSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication1.WSVerificarSaldo.VerificarSaldoResponse> VerificarSaldoAsync(MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSaldo", Namespace="http://www.BancoABC.com/VerificarSaldo/", Order=0)]
        public MvcApplication1.WSVerificarSaldo.VerificarSaldoRequestBody Body;
        
        public VerificarSaldoRequest() {
        }
        
        public VerificarSaldoRequest(MvcApplication1.WSVerificarSaldo.VerificarSaldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class VerificarSaldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double ValorFactura;
        
        public VerificarSaldoRequestBody() {
        }
        
        public VerificarSaldoRequestBody(int IdProducto, double ValorFactura) {
            this.IdProducto = IdProducto;
            this.ValorFactura = ValorFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSaldoResponse", Namespace="http://www.BancoABC.com/VerificarSaldo/", Order=0)]
        public MvcApplication1.WSVerificarSaldo.VerificarSaldoResponseBody Body;
        
        public VerificarSaldoResponse() {
        }
        
        public VerificarSaldoResponse(MvcApplication1.WSVerificarSaldo.VerificarSaldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BancoABC/EntidadComun")]
    public partial class VerificarSaldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Result;
        
        public VerificarSaldoResponseBody() {
        }
        
        public VerificarSaldoResponseBody(string Mensaje, bool Result) {
            this.Mensaje = Mensaje;
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerificarSaldoChannel : MvcApplication1.WSVerificarSaldo.VerificarSaldo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerificarSaldoClient : System.ServiceModel.ClientBase<MvcApplication1.WSVerificarSaldo.VerificarSaldo>, MvcApplication1.WSVerificarSaldo.VerificarSaldo {
        
        public VerificarSaldoClient() {
        }
        
        public VerificarSaldoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerificarSaldoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificarSaldoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificarSaldoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.WSVerificarSaldo.VerificarSaldoResponse MvcApplication1.WSVerificarSaldo.VerificarSaldo.VerificarSaldo(MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest request) {
            return base.Channel.VerificarSaldo(request);
        }
        
        public string VerificarSaldo(int IdProducto, double ValorFactura, out bool Result) {
            MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest inValue = new MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest();
            inValue.Body = new MvcApplication1.WSVerificarSaldo.VerificarSaldoRequestBody();
            inValue.Body.IdProducto = IdProducto;
            inValue.Body.ValorFactura = ValorFactura;
            MvcApplication1.WSVerificarSaldo.VerificarSaldoResponse retVal = ((MvcApplication1.WSVerificarSaldo.VerificarSaldo)(this)).VerificarSaldo(inValue);
            Result = retVal.Body.Result;
            return retVal.Body.Mensaje;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication1.WSVerificarSaldo.VerificarSaldoResponse> MvcApplication1.WSVerificarSaldo.VerificarSaldo.VerificarSaldoAsync(MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest request) {
            return base.Channel.VerificarSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.WSVerificarSaldo.VerificarSaldoResponse> VerificarSaldoAsync(int IdProducto, double ValorFactura) {
            MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest inValue = new MvcApplication1.WSVerificarSaldo.VerificarSaldoRequest();
            inValue.Body = new MvcApplication1.WSVerificarSaldo.VerificarSaldoRequestBody();
            inValue.Body.IdProducto = IdProducto;
            inValue.Body.ValorFactura = ValorFactura;
            return ((MvcApplication1.WSVerificarSaldo.VerificarSaldo)(this)).VerificarSaldoAsync(inValue);
        }
    }
}
